<?php

namespace spec\App\Entity;

use App\Entity\Customer;
use PhpSpec\ObjectBehavior;

class CustomerSpec extends ObjectBehavior
{
    public function getMatchers(): array
    {
        return parent::getMatchers(); // TODO: Change the autogenerated stub
    }

    function it_is_initializable()
    {
        $this->shouldHaveType(Customer::class);
    }

    function it_should_allow_to_set_name()
    {
        $this->setName("ExampleName");
        $this->getName()->shouldContain("ExampleName");
    }

}
